package com.indri.vsmentproject.data.model.report

import android.os.Parcelable
import kotlinx.parcelize.Parcelize

@Parcelize
data class LaporanModel(
    var id: String = "",              // ID Laporan (Auto-generated by Firebase)

    // Relasi (Penting untuk Query)
    val villa_id: String = "",
    val villa_nama: String = "",
    val area: String = "",
    val staff_id: String = "",
    val staff_nama: String = "",

    // Konten Laporan
    val tipe_laporan: String = "",    // "kerusakan" atau "stok_habis"
    val nama_barang: String = "",
    val keterangan: String = "",
    val prioritas: String = "Normal", // "Low", "Normal", "Urgent"

    // Bukti Visual (Cloudinary)
    val foto_url: String = "",        // URL foto bukti dari Cloudinary

    // Workflow / Status
    var status: String = "pending",   // "pending", "proses", "selesai", "ditolak"
    var catatan_manager: String = "", // Feedback dari Manager (misal: "Segera panggil tukang")

    // Timestamp
    val waktu_lapor: String = "",     // Format: yyyy-MM-dd HH:mm
    val waktu_selesai: String = ""    // Diisi saat status berubah jadi "selesai"
) : Parcelable